inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
